# Generated by Django 3.2.4 on 2021-07-06 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seekerbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seekerskillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('fresher', 'Fresher'), ('intermediate', 'iItermediate'), ('advance', 'Advance')], max_length=25)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekerbuilder.skillset')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('current_salary', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_title', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('job_location_state', models.CharField(max_length=50)),
                ('job_location_city', models.CharField(max_length=50)),
                ('job_location_country', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekerbuilder.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_degree_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('institute_university_name', models.CharField(max_length=255)),
                ('starting_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekerbuilder.seekerprofile')),
            ],
        ),
    ]
