# Generated by Django 3.2.4 on 2021-07-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0002_educationdetail_experiencedetail_seekerprofile_seekerskillset'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='currency',
            field=models.CharField(default='dollars', max_length=25),
            preserve_default=False,
        ),
    ]
