# Generated by Django 3.2.4 on 2021-07-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0003_seekerprofile_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seekerskillset',
        ),
    ]
