# Generated by Django 3.2.4 on 2021-07-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0004_delete_seekerskillset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillSet',
        ),
    ]
