# Generated by Django 3.2.4 on 2021-07-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0012_job_skillset_skillset'),
        ('seekerbuilder', '0005_delete_skillset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seekerskillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekerbuilder.seekerprofile')),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_management.skillset')),
            ],
        ),
    ]
