# Generated by Django 3.2.5 on 2021-07-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0006_seekerskillset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekerskillset',
            old_name='name',
            new_name='seeker',
        ),
        migrations.AddField(
            model_name='seekerskillset',
            name='skill_level',
            field=models.CharField(default='beginner', max_length=25),
            preserve_default=False,
        ),
    ]
