# Generated by Django 3.2.5 on 2021-07-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0007_auto_20210716_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seekerskillset',
            options={'verbose_name': 'Seeker skill set'},
        ),
    ]
