# Generated by Django 3.2.5 on 2021-07-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0008_alter_seekerskillset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='status',
            field=models.CharField(default='onhold', max_length=25),
            preserve_default=False,
        ),
    ]
