# Generated by Django 3.2.5 on 2021-07-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0009_seekerprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='status',
        ),
    ]
