# Generated by Django 3.2.5 on 2021-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0010_remove_seekerprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='photo',
            field=models.ImageField(default='\\Users\\atif\\Downloads\\1626264705038.jpg', upload_to='applicants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='resume',
            field=models.FileField(default='\\Users\\atif\\Downloads\\1626264705038.jpg', upload_to='applicants/documents'),
            preserve_default=False,
        ),
    ]
