# Generated by Django 3.2.5 on 2021-09-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0013_alter_seekerprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='current_salary',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='applicants/profile_pictures'),
        ),
    ]
