# Generated by Django 3.2.5 on 2021-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0014_auto_20210914_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='currency',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='current_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='applicants/documents'),
        ),
    ]
