# Generated by Django 3.2.5 on 2021-09-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0016_auto_20210916_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
    ]
