# Generated by Django 3.2.5 on 2021-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0017_seekerprofile_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerskillset',
            name='skill_set',
        ),
        migrations.AddField(
            model_name='seekerskillset',
            name='skill_name',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
