# Generated by Django 3.2.5 on 2021-09-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0018_auto_20210919_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedetail',
            name='total_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
