# Generated by Django 3.2.5 on 2021-09-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerbuilder', '0019_experiencedetail_total_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='description',
            field=models.TextField(default='this'),
            preserve_default=False,
        ),
    ]
