# Generated by Django 3.2.4 on 2021-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0003_auto_20210704_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('female', 'Female')], max_length=22),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('HR', 'recuriter'), ('job seeker', 'job_seeker')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='last_job_apply_date',
            field=models.DateField(null=True),
        ),
    ]
