# Generated by Django 3.2.4 on 2021-07-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0004_auto_20210705_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='last_login_date',
            field=models.DateTimeField(),
        ),
    ]
