# Generated by Django 3.2.4 on 2021-07-11 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0005_alter_userlog_last_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='last_job_apply_date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
