# Generated by Django 3.2.5 on 2021-09-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0007_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('HR', 'Recuriter'), ('job_seeker', 'Job_seeker')], default='job_seeker', max_length=255),
        ),
    ]
