# Generated by Django 3.2.5 on 2021-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0011_auto_20210913_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
    ]
