# Generated by Django 3.2.5 on 2021-09-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0014_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
