# Generated by Django 3.2.5 on 2021-09-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0015_alter_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='dated',
            new_name='sent_date',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
