# Generated by Django 3.2.5 on 2021-09-27 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0016_auto_20210927_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sent_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
