# Generated by Django 3.2.5 on 2021-09-27 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0018_auto_20210927_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethreads',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
