# Generated by Django 3.2.5 on 2021-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0019_messagethreads_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
