# Generated by Django 3.2.4 on 2021-07-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company'},
        ),
    ]
