# Generated by Django 3.2.4 on 2021-07-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buisnessstream',
            options={'verbose_name': 'BuisnessStream'},
        ),
        migrations.AlterModelOptions(
            name='companyimage',
            options={'verbose_name': 'CompanyImage'},
        ),
    ]
