# Generated by Django 3.2.5 on 2021-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0006_auto_20210913_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buisnessstream',
            name='company',
        ),
        migrations.AddField(
            model_name='buisnessstream',
            name='company',
            field=models.ManyToManyField(to='companyprofile.Company'),
        ),
    ]
