# Generated by Django 3.2.4 on 2021-07-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0004_auto_20210708_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTag',
        ),
    ]
