# Generated by Django 3.2.4 on 2021-07-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0005_delete_jobtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='title',
            field=models.CharField(default='backend engineer', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.ManyToManyField(to='job_management.JobPost')),
            ],
        ),
    ]
