# Generated by Django 3.2.4 on 2021-07-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0007_alter_jobpost_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=20000004, max_digits=10),
            preserve_default=False,
        ),
    ]
