# Generated by Django 3.2.4 on 2021-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0008_jobpost_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostactivity',
            name='apply_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
