# Generated by Django 3.2.4 on 2021-07-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0009_alter_jobpostactivity_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostactivity',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
