# Generated by Django 3.2.4 on 2021-07-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0011_jobpost_creater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_level', models.CharField(choices=[('beginner', 'BEGINNNER'), ('intermediate', 'INTERMEDIATE'), ('expert', 'EXPERT')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_management.jobpost')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_management.skillset')),
            ],
        ),
    ]
