# Generated by Django 3.2.4 on 2021-07-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0012_job_skillset_skillset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_skillset',
            old_name='skill_level',
            new_name='skill',
        ),
    ]
