# Generated by Django 3.2.4 on 2021-07-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0013_rename_skill_level_job_skillset_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillset',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='job_skillset',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'BEGINNNER'), ('intermediate', 'INTERMEDIATE'), ('expert', 'EXPERT')], default='advance', max_length=20),
            preserve_default=False,
        ),
    ]
