# Generated by Django 3.2.5 on 2021-07-15 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0004_alter_companyimage_image'),
        ('job_management', '0014_auto_20210712_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='cmpny_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companyprofile.company'),
        ),
    ]
