# Generated by Django 3.2.5 on 2021-07-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0015_alter_jobpost_cmpny_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_skillset',
            name='skill_level',
            field=models.CharField(max_length=20),
        ),
    ]
