# Generated by Django 3.2.5 on 2021-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0016_alter_job_skillset_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='status',
            field=models.CharField(default='onhold', max_length=25),
            preserve_default=False,
        ),
    ]
