# Generated by Django 3.2.5 on 2021-09-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_management', '0018_alter_jobpostactivity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_loc',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_type',
        ),
        migrations.AddField(
            model_name='joblocation',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_management.jobpost'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_posters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_management.jobpost'),
        ),
    ]
