# Generated by Django 3.2.5 on 2021-09-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0019_auto_20210913_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblocation',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
