# Generated by Django 3.2.5 on 2021-09-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0021_auto_20210916_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_management.jobpost'),
        ),
    ]
