# Generated by Django 3.2.5 on 2021-09-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0022_alter_jobtype_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_skillset',
            name='skill',
        ),
        migrations.AddField(
            model_name='job_skillset',
            name='skill_name',
            field=models.CharField(default='python developer', max_length=25),
            preserve_default=False,
        ),
    ]
