# Generated by Django 3.2.5 on 2021-09-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0023_auto_20210917_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(default='fulltime in office', max_length=40),
            preserve_default=False,
        ),
    ]
