# Generated by Django 3.2.5 on 2021-09-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0024_jobpost_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(default='fulltime - inoffice', max_length=40),
        ),
    ]
