# Generated by Django 3.2.5 on 2021-09-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0027_alter_jobpost_job_posters'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='direct_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
