# Generated by Django 3.2.5 on 2021-09-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0030_auto_20210920_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCategories',
        ),
    ]
