# Generated by Django 3.2.5 on 2021-09-20 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_management', '0031_delete_jobcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_posters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
