# Generated by Django 3.2.5 on 2021-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0032_alter_jobpost_job_posters'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_skillset',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
