# Generated by Django 3.2.5 on 2021-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0033_job_skillset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_description',
            field=models.TextField(null=True),
        ),
    ]
