# Generated by Django 3.2.5 on 2021-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0034_alter_jobpost_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='requirement_text',
            field=models.TextField(null=True),
        ),
    ]
