# Generated by Django 3.2.5 on 2021-09-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0038_jobalert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobalert',
            old_name='type',
            new_name='job_type',
        ),
    ]
